version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: workforce-hub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: workforce_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - workforce_hub_postgres_data:/var/lib/postgresql/data

volumes:
  workforce_hub_postgres_data:
