name: Build and deploy Node.js app to Azure Web App - workforce-hub-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Deploy server folder to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "workforce-hub-api"
          slot-name: "Production"
          package: server
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1D02B99A932F4C4CAC7394B20AF1DA3A }}